// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kqzttzqzwyczcgvwwnqe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtxenR0enF6d3ljemNndnd3bnFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwNDY0OTAsImV4cCI6MjA3MDYyMjQ5MH0.mSDVGG9pV-cwV6kSpcREdY0gOoaAebzdNJZGX5Wgki0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});